# version: '3.8'

services:

  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./migrations:/app/migrations  # Mount the migrations folder
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
